#!/bin/bash

ifconfig eth0 0
ip addr add 192.168.0.101/24 dev eth0
ip link add vxlan type vxlan id 1 group 239.0.0.1 ttl 4 port 0 0 dev eth0
ip addr add 10.10.11.21/24 dev vxlan
ip link set dev vxlan up
