#!/bin/bash

mkdir ../nas-srv-et-app
gcc -g3 ../nas-srv-et-sources/client/src/client.c \
../nas-srv-et-sources/client/src/client-func.c \
../nas-srv-et-lib/src/common-func.c \
../nas-srv-et-lib/src/crc.c \
../nas-srv-et-lib/src/protocol.c \
../nas-srv-et-lib/src/errors.c \
-o ../nas-srv-et-app/testClient
