#!/bin/bash

mkdir ../nas-srv-et-app
cp server_config.cfg ../nas-srv-et-app

gcc -g3 ../nas-srv-et-sources/server/src/server.c \
../nas-srv-et-sources/server/src/server-func.c \
../nas-srv-et-sources/server/src/netns-func.c \
../nas-srv-et-lib/src/common-func.c \
../nas-srv-et-lib/src/crc.c \
../nas-srv-et-lib/src/protocol.c \
../nas-srv-et-lib/src/errors.c \
-lconfig -o ../nas-srv-et-app/NAS-srv-et
